dir_path: "/home/lorenzo/git/rsl_panoptic_seg/panoptic_models/panoptic_models/detr"
frozen_weights: "/weights/detr_panoptic_model.pth"
lr_backbone: 0
backbone: "resnet50"
dilation: false
position_embedding: "sine"
enc_layers: 6
dec_layers: 6
dim_feedforward: 2048
hidden_dim: 256
dropout: 0.1
nheads: 8
num_queries: 100
pre_norm: false
masks: true
threshold: 0.85
aux_loss: true
set_cost_class: 1
set_cost_bbox: 5
set_cost_giou: 2
mask_loss_coef: 1
dice_loss_coef: 1
bbox_loss_coef: 5
giou_loss_coef: 2
eos_coef: 0.1
dataset_file: "coco_panoptic"
device: "cuda"

